spring.application.name=inventario
server.port=8080
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
# Configuración del Webhook de Automatización (n8n)
n8n.webhook.inventario-url=https://miguelbejarano.app.n8n.cloud/webhook/inventario-alerta
