spring.application.name=tornillo-feliz
# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://admin:Ferreteria@ferreteriafeliz.d84tqyy.mongodb.net/inventario?retryWrites=true&w=majority&appName=Ferreteriafeliz
spring.data.mongodb.database=inventario

# Server
server.port=8080

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
