spring.application.name=inventario
server.port=8080

# Nota que ahora es spring.mongodb.uri (sin el ".data")
spring.mongodb.uri=mongodb+srv://admin:Ferreteria@ferreteriafeliz.d84tqyy.mongodb.net/inventario?retryWrites=true&w=majoritycd 